### ISSUE TITLE
Temperature plotter 1 hour and 2 hour failing

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#23]
These two plot functions are not working.  The other plot functions all work.

**Comment by aransfor** [comment]
@jayich  As of February 19 the temperature reader has been unpowered and not taking data (this is when this issue was brought up) when there is no data in the time period the temp client fails. Perhaps this should be modified to alert people the temp client is down. Perhaps there was a power outage. Anyhow I re plugged in the monitor box and it immediatly started working
