### ISSUE TITLE
normalpmtflow

### ISSUE THREAD

**Issue by jayich** [CampbellGroup/common#5]
@aransfor 

For pmt.get_next_counts('ON', 1) we should be able to set a duration for which it will just return 0. kCts/second after.

**Comment by aransfor** [comment]
can this be fixed programatically in the experiment? such as

counts = pmt.get_next_counts('ON',1)
if:  counts
     print "these are the counts: ", counts
else:
    counts = 0
     print "counts are zero"

this is pretty explicit and doesnt rely on adding false counts. also it keeps versatility such as you could use

while not pmt.get_next_counts('ON',1):
        do something until counts arrive

**Comment by jayich** [comment]
I believe that it will hang indefinitely on:

counts = pmt.get_next_counts('ON',1)

I think a timeout needs to be set on the server.

**Comment by aransfor** [comment]
Thinking about this more the server should just have a timeout on that function that after .1 seconds returns None

**Comment by jayich** [comment]
It should return 0 kc/s after the timeout.  We don't want the user to have to error check for None.  A default timeout of 0.1 sounds fine.  This should be settable with something like:
>>> normalpmtflow.timeout(WithUnit(0.12, 's'))

and callable with
>>> normalmptflow.timeout()
Value(0.12, 's')

**Comment by aransfor** [comment]
@jayich I have looked extensively into this and get_next_counts does exactly what it says (it waits for the next counts and grabs it) This has to do with the pulser returning a time stamp versus an empty list. The problem with changing this to return a dummy 0.0 counts is that you cant store that data point in datavault since it doesnt have a time stamp and ALL PMT counts are saved as they should be. The correct fix would be to use the function cxn.pulser.get_pmt_counts(), this will return a time stamped list that is empty there were no counts. I think its important to keep the integrity of saving every PMT data point and not representing blank ones. Anywho cxn.pulser.get_pmt_counts() does explicitly what its name says as well as pmt.get_next_counts('ON',1)

**Comment by jayich** [comment]
Great.  I didn't realize there was a get_pmt_counts() function.
